Repository andela/king-kong-ah-frontend, pull requests merged in 2019-07, with the labels that each got.

#1 #166272054 setup webpack
  .eslintignore
  .eslintrc
  .gitignore
  README.md
  babel.config.js
  package-lock.json
  package.json
  src/index.css
  src/index.html
  src/index.js
  webpack.config.js
  webpack/filePaths.js
  webpack/webpack.common.js
  webpack/webpack.development.js
  webpack/webpack.production.js
Labels: Ready for review by TTL

#3 #166272058 setup react router
  package-lock.json
  package.json
  src/components/BaseRoute.jsx
  src/components/routes/index.js
  src/index.js
  src/pages/Homepage.jsx
  webpack/webpack.common.js
Labels: Ready for review

#2 #167043178 setup githint
  .githint.json
Labels: Ready for review by TTL

#4 #167072548 fix react route
  src/components/BaseRoute.jsx
  src/components/pages/Homepage.jsx
  src/core/routes.js
  webpack/webpack.common.js
Labels: Ready for review by TTL

#9 #167073294 add error overlay plugin
  package-lock.json
  package.json
  webpack/webpack.development.js
Labels: Ready for review by TTL

#10 #166272057 add basic test setup
  .gitignore
  .travis.yml
  README.md
  package-lock.json
  package.json
  src/config/assetsTransformer.js
  src/config/setupTests.js
  src/index.js
  src/index.spec.js
Labels: Ready for review by TTL

#11 #167118186 fix coverage badges
  .codeclimate.yml
  .travis.yml
  package-lock.json
  package.json
Labels: Ready for review by TTL

#12 #167117945 setup text atom
  package-lock.json
  package.json
  src/components/UI/atoms/Text/Text.jsx
  src/components/UI/atoms/Text/Text.md
  src/components/UI/atoms/Text/Text.spec.js
  src/components/pages/Homepage.jsx
  src/helpers/testUtils.js
  src/index.css
  src/index.js
  src/index.spec.js
  src/styles/GlobalStyle.jsx
  src/styles/ThemeWrapper/ThemeWrapper.jsx
  src/styles/variables/colorPalette.js
  src/styles/variables/fonts.js
  src/styles/variables/mainTheme.js
  src/styles/variables/spacing.js
  styleguide.config.js
  webpack/webpack.common.js
  webpack/webpack.development.js
Labels: Ready for review by TTL

#13 #16713220 set up heroku build
  Procfile
  app.js
  app.json
  package-lock.json
  package.json
Labels: Work in Progress

#14 #167132066 setup title atom
  src/components/UI/atoms/Title/Title.jsx
  src/components/UI/atoms/Title/Title.md
  src/components/UI/atoms/Title/Title.spec.js
  src/styles/variables/fonts.js
Labels: Ready for review by TTL

#19 #167192498 create divider atom
  src/components/UI/atoms/Divider/Divider.jsx
  src/components/UI/atoms/Divider/Divider.md
  src/components/UI/atoms/Divider/Divider.spec.js
  src/styles/variables/colorPalette.js
  src/styles/variables/mainTheme.js
  src/styles/variables/spacing.js
Labels: Ready for review by TTL

#17 #167169184 create FlexContainer atom
  package-lock.json
  src/components/UI/atoms/layouts/FlexContainer/FlexContainer.jsx
  src/components/UI/atoms/layouts/FlexContainer/FlexContainer.md
  src/components/UI/atoms/layouts/FlexContainer/FlexContainer.spec.js
  src/styles/GlobalStyle.jsx
  src/styles/variables/colorPalette.js
  src/styles/variables/mainTheme.js
  src/styles/variables/shadows.js
Labels: Ready for review by TTL

#20 #167189243 create image atom
  .travis.yml
  package-lock.json
  package.json
  public/assets/images/home.png
  src/components/UI/atoms/Image/Image.jsx
  src/components/UI/atoms/Image/Image.md
  src/components/UI/atoms/Image/Image.spec.js
  src/styles/variables/border.js
  src/styles/variables/colorPalette.js
  src/styles/variables/mainTheme.js
  src/styles/variables/shadows.js
  webpack/webpack.common.js
Labels: Ready for review by TTL

#16 #167142660 create icon atom
  package-lock.json
  package.json
  src/components/UI/atoms/Icon/Icon.jsx
  src/components/UI/atoms/Icon/Icon.md
  src/components/UI/atoms/Icon/Icon.spec.js
  src/components/UI/atoms/Title/Title.jsx
  src/fixtures/icons/Star.svg
  src/fixtures/icons/mockIcon.jsx
  src/styles/variables/colorPalette.js
  src/styles/variables/icons.js
  src/styles/variables/mainTheme.js
Labels: Ready for review by TTL

#18 #167191395 setup link atom
  package-lock.json
  src/components/UI/atoms/StyledLink/StyledLink.jsx
  src/components/UI/atoms/StyledLink/StyledLink.md
  src/components/UI/atoms/StyledLink/StyledLink.spec.js
  src/styles/variables/spacing.js
Labels: Ready for review by TTL

#24 #167271157 setup card divider molecule
  .eslintrc
  package-lock.json
  package.json
  src/components/UI/atoms/Divider/Divider.jsx
  src/components/UI/atoms/Divider/Divider.md
  src/components/UI/atoms/Divider/Divider.spec.js
  src/components/UI/molecules/CardDivider/CardDivider.jsx
  src/components/UI/molecules/CardDivider/CardDivider.md
  src/components/UI/molecules/CardDivider/CardDivider.spec.js
  src/styles/variables/fonts.js
  styleguide.config.js
  webpack/webpack.common.js
Labels: Ready for review by TTL

#26 #167276162 Create inputForm Field molecule
  package-lock.json
  package.json
  src/components/UI/atoms/Icon/Icon.jsx
  src/components/UI/atoms/InputField/InputField.jsx
  src/components/UI/atoms/layouts/FlexContainer/FlexContainer.jsx
  src/components/UI/molecules/InputTextField/InputTextField.jsx
  src/components/UI/molecules/InputTextField/InputTextField.md
  src/components/UI/molecules/InputTextField/InputTextField.spec.js
  src/components/UI/molecules/label/Label.jsx
  src/components/UI/molecules/label/Label.md
  src/components/UI/molecules/label/Label.spec.js
  src/styles/variables/colorPalette.js
  src/styles/variables/fonts.js
  webpack/webpack.common.js
Labels: Ready for review by TTL

#31 #167303083 create useForm hook
  package-lock.json
  package.json
  src/fixtures/useForm.js
  src/hooks/tests/useForm.spec.js
  src/hooks/useForm.js
Labels: Ready for review by TTL

#38 #167343492 setup protected route for the app
  src/components/BaseRoute.jsx
  src/components/ProtectedRoute.jsx
  src/components/pages/Protected.jsx
  src/components/pages/Protected.spec.js
  src/core/routes.js
  src/index.spec.js
Labels: Ready for review

#40 #167356585 create useDataFromApi hook
  __mocks__/axios.js
  __mocks__/useDataFromApi.js
  package-lock.json
  package.json
  src/api/api.js
  src/constants/constants.js
  src/fixtures/sideEffect.js
  src/helpers/requestApi.js
  src/hooks/tests/useApiData.spec.js
  src/hooks/tests/useDataFromApi.spec.js
  src/hooks/useApiData.js
  src/hooks/useDataFromApi.js
  webpack/webpack.common.js
Labels: Ready for review

#37 #167350084 setup search bar
  package-lock.json
  src/components/UI/atoms/Icon/Icon.jsx
  src/components/UI/atoms/InputField/InputField.jsx
  src/components/UI/atoms/InputField/InputField.md
  src/components/UI/atoms/layouts/FlexContainer/FlexContainer.jsx
  src/components/UI/molecules/SearchBar/SearchBar.jsx
  src/components/UI/molecules/SearchBar/SearchBar.md
  src/components/UI/molecules/SearchBar/SearchBar.spec.js
  src/styles/variables/colorPalette.js
  src/styles/variables/icons.js
  src/styles/variables/spacing.js
Labels: Ready for review

#32 #167212749 create page layout
  package-lock.json
  package.json
  src/components/BaseRoute.jsx
  src/components/UI/atoms/Button/Button.jsx
  src/components/UI/atoms/Button/Button.spec.js
  src/components/UI/atoms/InputField/InputField.jsx
  src/components/UI/atoms/StyledLink/StyledLink.jsx
  src/components/UI/atoms/Text/Text.jsx
  src/components/UI/atoms/Title/Title.jsx
  src/components/UI/atoms/layouts/FlexContainer/FlexContainer.jsx
  src/components/UI/molecules/Headers/HeaderNavigation.jsx
  src/components/UI/molecules/Headers/HeaderNavigation.md
  src/components/UI/molecules/Headers/HeaderNavigation.spec.js
  src/components/UI/organisms/Header/Header.jsx
  src/components/UI/organisms/Header/Header.md
  src/components/UI/organisms/Header/Header.spec.js
  src/components/pages/Home/HomePage.jsx
  src/components/pages/Home/HomePage.spec.js
  src/components/pages/Home/navItems.js
  src/components/pages/Homepage.jsx
  src/components/templates/PageLayout/PageLayout.jsx
  src/components/templates/PageLayout/PageLayout.spec.js
  src/components/templates/PageLayout/PageLoader.jsx
  src/core/routes.js
  src/fixtures/navItems.js
  src/helpers/displayLoader.js
  src/helpers/headerMapper.js
  src/index.spec.js
  src/styles/GlobalStyle.jsx
  src/styles/variables/mainTheme.js
  src/styles/variables/mediaQueries.js
  src/styles/variables/spacing.js
  styleguide.config.js
  webpack/webpack.common.js
Labels: Ready for review by TTL

#42 #167414051 Refactor mocks and test files
  package.json
  src/__mocks__/axios.js
  src/__mocks__/useDataFromApi.js
  src/components/templates/PageLayout/PageLayout.jsx
  src/fixtures/navItems.js
  src/fixtures/sideEffect.js
  src/hooks/tests/useDataFromApi.spec.js
  src/hooks/tests/useForm.spec.js
  src/hooks/useDataFromApi.js
Labels: Ready for review

#45 #167459291 create rating count component
  package-lock.json
  package.json
  src/components/UI/atoms/RatingsCount/RatingsCount.jsx
  src/components/UI/atoms/RatingsCount/RatingsCount.md
  src/components/UI/atoms/RatingsCount/RatingsCount.spec.js
  src/components/UI/atoms/Text/Text.jsx
  src/components/UI/atoms/layouts/FlexContainer/FlexContainer.jsx
  src/components/UI/molecules/RatingBlock/RatingBlock.jsx
  src/components/UI/molecules/RatingBlock/RatingBlock.md
  src/components/UI/molecules/RatingBlock/RatingBlock.spec.js
  src/components/UI/molecules/RatingHeadings/RatingHeadings.jsx
  src/components/UI/molecules/RatingHeadings/RatingHeadings.md
  src/components/UI/molecules/RatingHeadings/RatingHeadings.spec.js
  src/components/UI/organisms/RatingGroup/RatingGroup.jsx
  src/components/UI/organisms/RatingGroup/RatingGroup.md
  src/components/UI/organisms/RatingGroup/RatingGroup.spec.js
  src/components/UI/organisms/RatingsSection/RatingsSection.jsx
  src/components/UI/organisms/RatingsSection/RatingsSection.md
  src/components/UI/organisms/RatingsSection/RatingsSection.spec.js
  src/components/pages/Home/HomePage.jsx
  src/components/templates/PageLayout/PageLayout.jsx
  src/styles/GlobalStyle.jsx
  src/styles/variables/colorPalette.js
  src/styles/variables/fonts.js
  src/styles/variables/spacing.js
Labels: Ready for review by TTL

#47 #167450752 create article card
  public/assets/images/adventure-california-canyon-2397414.jpg
  public/assets/images/camera-fashion-man-2420231.jpg
  public/assets/images/cash-collection-currency-47344.jpg
  public/assets/images/woman-on-beach.jpeg
  src/components/UI/atoms/Text/Text.jsx
  src/components/UI/atoms/Title/Title.jsx
  src/components/UI/molecules/ArticleCard/ArticleCard.jsx
  src/components/UI/molecules/ArticleCard/ArticleCard.md
  src/components/UI/molecules/StarRating/StarRating.jsx
  src/components/UI/molecules/StarRating/StarRating.md
  src/styles/variables/colorPalette.js
  src/styles/variables/fonts.js
  src/styles/variables/icons.js
  src/styles/variables/mainTheme.js
  src/styles/variables/spacing.js
  src/styles/variables/width.js
Labels: Ready for review by TTL

#46 #167454777 create image with article row component
  package-lock.json
  src/components/UI/atoms/Text/Text.jsx
  src/components/UI/atoms/Title/Title.jsx
  src/components/UI/atoms/layouts/FlexContainer/FlexContainer.jsx
  src/components/UI/molecules/ArticleContent/ArticleContent.jsx
  src/components/UI/molecules/ArticleContent/ArticleContent.md
  src/components/UI/molecules/ArticleContent/ArticleContent.spec.js
  src/components/UI/molecules/ImageText/ImageText.jsx
  src/components/UI/molecules/ImageText/ImageText.md
  src/components/UI/molecules/ImageText/ImageText.spec.js
  src/components/UI/molecules/SearchBar/SearchBar.spec.js
  src/components/pages/Home/HomePage.jsx
  src/styles/variables/colorPalette.js
  src/styles/variables/fonts.js
  src/styles/variables/spacing.js
  src/styles/variables/width.js
Labels: Ready for review by TTL

#43 #167326021 add authentication feature
  package-lock.json
  package.json
  public/assets/images/home copy.png
  public/assets/images/home.png
  public/assets/images/home1.png
  public/assets/images/homepage.png
  src/HOC/withCheckAuth.jsx
  src/HOC/withCheckAuth.spec.js
  src/__mocks__/axios.js
  src/__mocks__/fileMock.js
  src/__mocks__/requestApi.js
  src/components/UI/atoms/Button/Button.jsx
  src/components/UI/atoms/Button/Button.spec.js
  src/components/UI/atoms/InputField/InputField.jsx
  src/components/UI/atoms/Text/Text.jsx
  src/components/UI/atoms/layouts/FlexContainer/FlexContainer.jsx
  src/components/UI/atoms/layouts/FlexContainer/FlexContainer.spec.js
  src/components/UI/molecules/ButtonRow/ButtonRow.jsx
  src/components/UI/molecules/ButtonRow/ButtonRow.spec.js
  src/components/UI/molecules/Form/Form.jsx
  src/components/UI/molecules/Form/Form.md
  src/components/UI/molecules/Form/Form.spec.js
  src/components/UI/molecules/Headers/HeaderNavigation.jsx
  src/components/UI/molecules/ImageText/ImageText.jsx
  src/components/UI/molecules/InputTextField/InputTextField.jsx
  src/components/UI/molecules/SearchBar/SearchBar.jsx
  src/components/UI/molecules/SearchBar/SearchBar.spec.js
  src/components/UI/molecules/label/Label.jsx
  src/components/UI/organisms/AuthForm/AuthForm.jsx
  src/components/UI/organisms/AuthForm/AuthForm.md
  src/components/UI/organisms/AuthForm/AuthForm.spec.js
  src/components/UI/organisms/AuthForm/buttonRowItem.js
  src/components/UI/organisms/Header/Header.jsx
  src/components/UI/organisms/RatingsSection/RatingsSection.jsx
  src/components/UI/organisms/WelcomeSection/WelcomeSection.jsx
  src/components/UI/organisms/WelcomeSection/WelcomeSection.md
  src/components/UI/organisms/WelcomeSection/WelcomeSection.spec.js
  src/components/pages/AuthPages/Login.jsx
  src/components/pages/AuthPages/Login.spec.js
  src/components/pages/AuthPages/Signup.jsx
  src/components/pages/AuthPages/Signup.spec.js
  src/components/pages/AuthPages/loginItems.js
  src/components/pages/AuthPages/navItems.js
  src/components/pages/AuthPages/signupItems.js
  src/components/pages/Home/HomePage.jsx
  src/components/pages/Home/navItems.js
  src/components/pages/UserPage/UserPage.jsx
  src/components/pages/UserPage/UserPage.spec.js
  src/components/pages/UserPage/navItems.js
  src/components/templates/PageLayout/PageLayout.jsx
  src/core/routes.js
  src/fixtures/navItems.js
  src/helpers/headerMapper.js
  src/hooks/tests/useDataFromApi.spec.js
  src/index.js
  src/styles/GlobalStyle.jsx
  src/styles/variables/fonts.js
  src/styles/variables/icons.js
  src/styles/variables/width.js
  webpack/webpack.common.js
Labels: Work in Progress

#44 #167482351 add tag row feature
  src/components/UI/atoms/StyledLink/StyledLink.jsx
  src/components/UI/molecules/TagRow/TagRow.jsx
  src/components/UI/molecules/TagRow/TagRow.md
  src/components/UI/molecules/TagRow/TagRow.spec.js
  src/styles/variables/colorPalette.js
Labels: Ready for review by TTL

#49 #167519929 create homepage footer components
  app.js
  package-lock.json
  package.json
  src/api/api.js
  src/components/UI/atoms/Icon/Icon.jsx
  src/components/UI/atoms/Icon/Icon.spec.js
  src/components/UI/atoms/RatingsCount/RatingsCount.spec.js
  src/components/UI/atoms/StyledLink/StyledLink.jsx
  src/components/UI/atoms/Text/Text.jsx
  src/components/UI/atoms/Text/Text.spec.js
  src/components/UI/atoms/Title/Title.jsx
  src/components/UI/atoms/Title/Title.spec.js
  src/components/UI/atoms/layouts/FlexContainer/FlexContainer.jsx
  src/components/UI/atoms/layouts/FlexContainer/FlexContainer.spec.js
  src/components/UI/molecules/Footer/About/About.jsx
  src/components/UI/molecules/Footer/About/About.md
  src/components/UI/molecules/Footer/About/About.spec.js
  src/components/UI/molecules/Footer/Menu/Menu.jsx
  src/components/UI/molecules/Footer/Menu/Menu.md
  src/components/UI/molecules/Footer/Menu/Menu.spec.js
  src/components/UI/molecules/Footer/Social/Social.jsx
  src/components/UI/molecules/Footer/Social/Social.md
  src/components/UI/molecules/Footer/Social/Social.spec.js
  src/components/UI/molecules/IconRow/IconRow.jsx
  src/components/UI/molecules/IconRow/IconRow.md
  src/components/UI/molecules/IconRow/IconRow.spec.js
  src/components/UI/organisms/Footer/Footer.jsx
  src/components/UI/organisms/Footer/Footer.md
  src/components/UI/organisms/Footer/Footer.spec.js
  src/components/pages/Home/HomePage.jsx
  src/components/pages/Home/footerItems.js
  src/components/templates/PageLayout/PageLayout.jsx
  src/constants/constants.js
  src/helpers/requestApi.js
  src/styles/variables/colorPalette.js
  src/styles/variables/icons.js
  src/styles/variables/width.js
  webpack/webpack.development.js
Labels: Ready for review
